---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise64_vmware
    box_url: http://files.vagrantup.com/precise64_vmware.box

suites:
- name: default
  run_list: ["recipe[autossh]"]
  attributes: {}
